// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─── Android (from google-services.json) ──────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdsHFRRH6pODUzum5_SWbzKWGWvwZbHU',
    appId: '1:83889955513:android:536366e2e5cac62a02b168',
    messagingSenderId: '83889955513',
    projectId: 'audio-e89f0',
    storageBucket: 'audio-e89f0.firebasestorage.app',
  );

  // ─── Web (fallback — same project) ────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcdsHFRRH6pODUzum5_SWbzKWGWvwZbHU',
    appId: '1:83889955513:android:536366e2e5cac62a02b168',
    messagingSenderId: '83889955513',
    projectId: 'audio-e89f0',
    storageBucket: 'audio-e89f0.firebasestorage.app',
    authDomain: 'audio-e89f0.firebaseapp.com',
  );

  // ─── iOS (fallback — same project) ────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcdsHFRRH6pODUzum5_SWbzKWGWvwZbHU',
    appId: '1:83889955513:android:536366e2e5cac62a02b168',
    messagingSenderId: '83889955513',
    projectId: 'audio-e89f0',
    storageBucket: 'audio-e89f0.firebasestorage.app',
    iosBundleId: 'com.example.audio_player',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcdsHFRRH6pODUzum5_SWbzKWGWvwZbHU',
    appId: '1:83889955513:android:536366e2e5cac62a02b168',
    messagingSenderId: '83889955513',
    projectId: 'audio-e89f0',
    storageBucket: 'audio-e89f0.firebasestorage.app',
    iosBundleId: 'com.example.audio_player',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcdsHFRRH6pODUzum5_SWbzKWGWvwZbHU',
    appId: '1:83889955513:android:536366e2e5cac62a02b168',
    messagingSenderId: '83889955513',
    projectId: 'audio-e89f0',
    storageBucket: 'audio-e89f0.firebasestorage.app',
    authDomain: 'audio-e89f0.firebaseapp.com',
  );
}
